event_inherited();
global.playerDMG = 20;
global.max_player_hp = 100;
global.playerSpeed = 2.5;
global.playerCooldown = 32;
global.enemyDMG = 12;
global.enemyHP = 70;
global.enemySpeed = 2.15;
global.enemyCooldown = 55;
global.player_hp = 100;