event_inherited();
global.playerDMG = 15;
global.max_player_hp = 80;
global.playerSpeed = 2.2;
global.playerCooldown = 40;
global.enemyDMG = 12;
global.enemyHP = 100;
global.enemySpeed = 2.5;
global.enemyCooldown = 40;
global.player_hp = 80;